### ISSUE TITLE
Not working with etherpad-lite-1.5.7

### ISSUE THREAD

**Issue by frediz** [JohnMcLear/etherpad-cli-client#2]
Hi,
it doesn't seem to work on my etherpad-lite instance (version 1.5.7).
Am I missing something ?
I launch it like this : 
$ ~/node_modules/.bin/etherpad  http://server:9001/p/test -a "blabla"

but it doesn't return nor display anything.
$ nodejs -v
v0.10.29
$ npm -v
1.4.21

Fred

**Comment by JohnMcLear** [comment]
hrm bummer I will take a look

**Comment by JohnMcLear** [comment]
Works fine..  Did you put your Etherpad in ``loadTest`` mode as per the readme?????
